const app = document.querySelector('#app');
const toast = document.querySelector('#toast');
let toastTimer;
let state = { view: 'landing', selected: 'dashboard' };

const navItems = [
    ['dashboard', '⌂', 'Overview'], ['schedule', '◷', 'Jadwal'], ['tasks', '✓', 'Tugas'],
    ['ai-plan', '✦', 'Rencana AI'], ['assistant', '◌', 'Asisten AI'], ['materials', '▣', 'Materi & File'],
    ['subjects', '◒', 'Mata Pelajaran'], ['analysis', '◩', 'Analisis Belajar'], ['settings', '⚙', 'Pengaturan']
];
const imageUrl = (id) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=80`;

function showToast(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 2600); }
function go(view) { state.view = view; render(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function authForm(mode) { return `<div class="shell"><div class="topbar"><button class="brand" data-action="landing"><span class="brand-mark">S</span><span>Student AI <small>ASSISTANT</small></span></button><button class="ghost-btn" data-action="landing">← Kembali</button></div><section class="form-card glass"><span class="label">${mode === 'login' ? 'Welcome back' : 'Start your orbit'}</span><h1>${mode === 'login' ? 'Masuk ke ruang belajarmu.' : 'Bikin ruang belajarmu.'}</h1><p>${mode === 'login' ? 'Semua jadwal, fokus, dan insight belajar kamu tersimpan di satu tempat.' : 'Student AI Assistant membantu kamu mengubah tugas yang ramai menjadi langkah yang terasa ringan.'}</p><div class="form-group"><label>Email</label><input id="email" type="email" placeholder="nama@email.com" value="${mode === 'login' ? 'alex@student.id' : ''}"></div><div class="form-group"><label>Password</label><input type="password" placeholder="••••••••" value="studyflow"></div><button class="primary-btn" data-action="auth-submit">${mode === 'login' ? 'Masuk ke dashboard  →' : 'Buat akun gratis  →'}</button><div class="form-foot">${mode === 'login' ? 'Belum punya akun?' : 'Sudah punya akun?'} <button data-action="toggle-auth">${mode === 'login' ? 'Daftar sekarang' : 'Masuk di sini'}</button></div></section></div>`; }
function landing() { return `<div class="shell"><header class="topbar"><button class="brand" data-action="landing"><span class="brand-mark">S</span><span>Student AI <small>ASSISTANT</small></span></button><div class="nav-actions"><button class="ghost-btn" data-action="login">Masuk</button><button class="primary-btn" data-action="register">Mulai gratis  ↗</button></div></header><section class="hero"><div><span class="label">Student AI assistant / 2026</span><h1>Belajar lebih <em>nyambung</em> dengan hidupmu.</h1><p class="hero-copy">Student AI Assistant menyatukan jadwal, tugas, materi, dan refleksi belajar ke dalam satu ruang yang adaptif. AI-nya bantu kamu mulai, bukan mengambil alih.</p><div class="hero-buttons"><button class="primary-btn" data-action="register">Masuk ke Student AI  →</button><button class="pill-btn" data-action="demo">Lihat demo singkat ◉</button></div><div class="metric-strip"><div class="metric"><strong>24/7</strong><span>teman berpikir</span></div><div class="metric"><strong>03m</strong><span>rata-rata mulai</span></div><div class="metric"><strong>86%</strong><span>fokus mingguan</span></div></div></div><div class="visual-stage"><div class="hero-tag">hari ini <b>+18 fokus menit</b></div><div class="orbit"></div><div class="image-card card-main"><img alt="Student studying at a desk" src="${imageUrl('1522202176988-66273c2fd55f')}"></div><div class="image-card card-side"><img alt="Notes and coffee" src="${imageUrl('1456324504439-367cee3b3c32')}"></div><div class="image-card card-mini"><img alt="Creative study materials" src="${imageUrl('1499750310107-5fef28a66643')}"></div></div></section><div class="trusted">built for curious minds · from first draft to final answer</div></div>`; }
function sidebar() { return `<aside class="sidebar glass"><div class="side-brand"><button class="brand" data-action="dashboard"><span class="brand-mark">S</span><span>Student AI <small>ASSISTANT</small></span></button></div><nav class="side-nav">${navItems.map(([id, icon, label]) => `<button class="nav-item ${state.selected === id ? 'active' : ''}" data-view="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join('')}</nav><div class="side-bottom"><div class="profile"><div class="avatar">AR</div><div><strong>Alex R.</strong><span>student / curious</span></div></div><button class="logout" data-action="landing">↪ Keluar</button></div></aside>`; }
function dashboard() { return `<div class="greeting"><div><span class="label">Monday, 12 January 2026</span><h1>Selamat pagi, Alex.</h1></div><p>Kamu punya ruang yang cukup untuk maju hari ini. Kita mulai dari satu hal kecil?</p></div><div class="grid dashboard-grid"><button class="tile glass focus-tile" data-view="assistant"><span class="label">Focus pulse</span><h3>22 menit fokus</h3><p>Lanjutkan sesi <b>Biologi · Sel</b> yang tertunda kemarin.</p><span class="tile-arrow">↗</span><div class="focus-ring"></div></button><button class="tile glass task-tile" data-view="tasks"><span class="label">Due soon</span><h3>3 tugas</h3><p>Yang paling dekat: Esai Sosiologi</p><span class="tile-arrow">↗</span></button><button class="tile glass plan-tile" data-view="ai-plan"><span class="label">AI plan</span><h3>1 rencana</h3><p>Rencana belajar UTBK siap ditinjau.</p><span class="tile-arrow">↗</span></button></div><div class="section-row"><h3>Agenda kamu</h3><button class="text-btn" data-view="schedule">Lihat semua →</button></div><div class="schedule-list"><button class="schedule-card glass" data-view="schedule"><span class="time"><i class="dot"></i>09:00 — 10:30</span><h4>Matematika Lanjut</h4><p>Ruang 04 · bersama Nadia</p></button><button class="schedule-card glass" data-view="tasks"><span class="time"><i class="dot lime"></i>11:00 — 12:00</span><h4>Kerjakan esai Sosiologi</h4><p>Deadline besok · 60% selesai</p></button><button class="schedule-card glass" data-view="ai-plan"><span class="time"><i class="dot coral"></i>16:00 — 16:45</span><h4>Review dengan AI</h4><p>Rencana UTBK · sesi 03</p></button></div><div class="section-row"><h3>Progress minggu ini</h3><span class="label">72% complete</span></div><div class="glass" style="padding:18px;border-radius:16px"><div class="progress-bar"><i style="width:72%"></i></div></div>`; }
function content(view) { const contentMap = { schedule: ['Jadwal kamu', 'Ruang untuk ritme yang realistis.', '◷', 'Jadwal hari ini', ['Matematika Lanjut', 'Bahasa Inggris', 'Review Biologi']], tasks: ['Tugas & deadline', 'Pecah tugas besar jadi langkah yang bisa dimulai.', '✓', 'Antrian tugas', ['Esai Sosiologi', 'Problem Set Kalkulus', 'Presentasi Sejarah']], materials: ['Materi & file', 'Semua referensi, tanpa tab yang tercecer.', '▣', 'Perpustakaan kamu', ['Biologi — Sel & Genetika', 'Catatan Kalkulus Bab 4', 'Brief Presentasi Sejarah']], subjects: ['Mata pelajaran', 'Lihat pola belajar kamu per subjek.', '◒', 'Subject map', ['Matematika Lanjut', 'Sosiologi', 'Biologi', 'Bahasa Inggris']], settings: ['Pengaturan', 'Ruang kecil untuk mengatur cara LUMA menemani.', '⚙', 'Preferensi', ['Notifikasi & reminder', 'Profil belajar', 'Privasi data']], analysis: ['Analisis belajar', 'Insight yang membantu kamu kenal cara belajarmu.', '◩', 'Weekly signal', ['Fokus terbaik: 09:00—11:00', 'Topik kuat: Biologi', 'Saran: jeda lebih konsisten']] }; const data = contentMap[view] || contentMap.schedule; return `<div class="page-header"><div><span class="label">${data[2]} LUMA module</span><h1>${data[0]}</h1><p>${data[1]}</p></div><span class="date-chip">12 JAN 2026 · LIVE</span></div><div class="content-grid"><section class="list-card glass"><div class="section-row" style="margin-top:0"><h3>${data[3]}</h3><button class="text-btn" data-action="notify">+ Tambah</button></div>${data[4].map((item, i) => `<div class="list-item"><div class="item-icon">${i === 0 ? data[2] : '↗'}</div><div><strong>${item}</strong><span>${view === 'tasks' ? ['Due tomorrow · 60% complete', 'Due Friday · not started', 'Due next week · 20% complete'][i] : 'Updated just now · synced'}</span></div><span class="status">${i === 0 ? 'ACTIVE' : 'OPEN'}</span></div>`).join('')}</section><aside class="detail-panel glass"><span class="label">next up</span><h3>${data[4][0]}</h3><p>Setiap langkah kecil yang kamu ambil akan muncul sebagai konteks baru untuk AI assistant-mu.</p><div class="progress-wrap"><div class="section-row" style="margin:0 0 9px"><span class="muted" style="font-size:11px">Momentum</span><span class="label">${view === 'analysis' ? '86%' : '60%'}</span></div><div class="progress-bar"><i style="width:${view === 'analysis' ? '86' : '60'}%"></i></div></div><button class="primary-btn" style="margin-top:28px" data-action="notify">Buka detail →</button></aside></div>`; }
function aiPlan() { return `<div class="page-header"><div><span class="label">✦ AI co-pilot</span><h1>Rencana yang terasa mungkin.</h1><p>Ceritakan tujuanmu. LUMA akan bantu menyusun langkah, waktu, dan jeda.</p></div><span class="date-chip">SMART MODE · ON</span></div><div class="ai-box glass"><span class="label">prompt studio</span><h3 style="font:600 27px 'Space Grotesk';letter-spacing:-.05em;margin:10px 0">Apa yang ingin kamu selesaikan?</h3><div class="ai-input"><input id="plan-prompt" placeholder="Contoh: kuasai 3 bab kalkulus sebelum Jumat"><button class="primary-btn" data-action="generate">Generate ✦</button></div><div class="ai-response" id="ai-response" style="display:none"></div></div>`; }
function assistant() { return `<div class="page-header"><div><span class="label">◌ always in context</span><h1>Asisten AI</h1><p>Teman berpikir yang tahu jadwal, tugas, dan ritme belajarmu.</p></div></div><div class="ai-box glass"><span class="label">luma is listening</span><h3 style="font:600 27px 'Space Grotesk';letter-spacing:-.05em;margin:10px 0">Hai Alex. Mau mulai dari mana?</h3><div class="ai-response">“Berdasarkan fokusmu minggu ini, aku menyarankan kita mulai dari satu soal Kalkulus. Tidak perlu menyelesaikan semuanya sekarang.”</div><div class="ai-input"><input id="assistant-prompt" placeholder="Tulis pertanyaan atau stuck-mu..."><button class="primary-btn" data-action="ask">Kirim ↗</button></div></div>`; }
function analysis() { return `<div class="page-header"><div><span class="label">◩ signal, not judgment</span><h1>Analisis belajar</h1><p>Lihat pola tanpa menghakimi progresmu.</p></div></div><div class="glass" style="padding:22px;border-radius:18px"><div class="section-row" style="margin-top:0"><h3>Jam fokus per hari</h3><span class="label">last 7 days</span></div><div class="analysis-chart">${[42, 65, 55, 82, 73, 94, 58].map((height, i) => `<div class="bar" style="height:${height}%"><span>${['M', 'S', 'R', 'K', 'J', 'S', 'M'][i]}</span></div>`).join('')}</div></div>`; }
function appView() { const view = state.selected; let inner = view === 'dashboard' ? dashboard() : view === 'ai-plan' ? aiPlan() : view === 'assistant' ? assistant() : view === 'analysis' ? analysis() : content(view); return `<div class="app-shell"><div>${sidebar()}</div><section class="workspace"><div class="workspace-top"><span class="brand"><span class="brand-mark">L</span><span>My learning space</span></span><span class="date-chip">⌘ K · command center</span></div>${inner}</section></div>`; }
function render() { app.innerHTML = state.view === 'landing' ? landing() : state.view === 'login' ? authForm('login') : state.view === 'register' ? authForm('register') : appView(); }

document.addEventListener('click', (event) => { const target = event.target.closest('[data-action], [data-view]'); if (!target) return; const action = target.dataset.action; const view = target.dataset.view; if (view) { state.selected = view; state.view = 'app'; render(); return; } if (action === 'landing') go('landing'); if (action === 'login') go('login'); if (action === 'register') go('register'); if (action === 'toggle-auth') go(state.view === 'login' ? 'register' : 'login'); if (action === 'auth-submit') { state.selected = 'dashboard'; go('app'); showToast('Welcome ke ruang belajarmu.'); } if (action === 'demo') { showToast('Demo mode: klik kartu agenda untuk menjelajah.'); } if (action === 'notify') showToast('Fitur ini siap dipakai di sesi berikutnya.'); if (action === 'generate') { const prompt = document.querySelector('#plan-prompt')?.value || 'kuasai 3 bab kalkulus sebelum Jumat'; const response = document.querySelector('#ai-response'); response.style.display = 'block'; response.innerHTML = `<b>Rencana 3 langkah untuk “${prompt}”</b><br>1. 25 menit: pahami konsep inti · 2. 10 menit: jeda aktif · 3. 25 menit: kerjakan 3 soal bertingkat. Aku sudah menaruhnya di jadwal Rabu sore.`; showToast('Rencana AI berhasil dibuat.'); } if (action === 'ask') { const input = document.querySelector('#assistant-prompt'); if (input && input.value) { showToast('Pertanyaanmu sudah masuk ke konteks LUMA.'); input.value = ''; } } });
render();
